<?php
/*********************************************************************************************
*  Mbit Studio j.d.o.o 
*  Dragutina Golika 63 
*  10000, Zagreb Croatia
*  Email: contact [@] mbit.io
*  Author: Jerko Puratic - jerko.puratic@mbit.io
*  Web: http://www.mbit.io
*
*  Transformer $className$ autogenerated by phalcon-devtools(Mbit version) with (CRUD) actions
*
*********************************************************************************************/

use App\$className$\Models\$className$Model;
use App\$className$\Processors\$className$Processor;

use League\Fractal\TransformerAbstract;
//use App\Foobar\Transformers\ItemTransformer;

class $className$Transformer extends TransformerAbstract
{
    //protected $defaultIncludes = [
        //'items'
    //];

    public function transform($className$Model $singularVar$)
    {

        return [
            $assignInputFromRequestTransform$'links'           => [
                [
                    'rel' => 'self',
                    'uri' => '/$className$/' . $singularVar$->id,
                ]
            ]
        ];
    }

    /**
     * Include Items
     *
     * @return League\Fractal\ItemResource
     */
    //public function includeItems(UserModel $user)
    //{
    //    $items = $user->items;

    //    return $this->collection($items, new ItemTransformer);
    //}
}
